# Generated by Django 5.2.1 on 2025-05-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_caregiverprofile_availability_availabilityslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined_by_family', 'Declined by Family'), ('declined_by_caregiver', 'Declined by Caregiver')], default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_match_requests', to='profiles.caregiverprofile')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_match_requests', to='profiles.familyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('family', 'caregiver'), name='unique_pending_request_family_caregiver')],
                'unique_together': {('family', 'caregiver', 'status')},
            },
        ),
    ]
