# Generated by Django 5.2.1 on 2025-05-25 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.caregiverprofile')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='profiles.familyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('caregiver', 'family')},
            },
        ),
    ]
